function manifest = Require_surprise_source_manifest(projectRoot, source)
%REQUIRE_SURPRISE_SOURCE_MANIFEST Prevent mixed-source downstream reruns.

    if nargin < 2 || isempty(source)
        source = Surprise_source_config(projectRoot);
    end
    manifestFile = fullfile(projectRoot, 'Output', 'manifests', ...
        'surprise_source_manifest.csv');
    if exist(manifestFile, 'file') ~= 2
        error(['SURPRISE_SOURCE_MANIFEST_MISSING: run Step 6 with the selected ' ...
            'SURPRISE_SOURCE before downstream policy-data steps.']);
    end

    manifest = readtable(manifestFile, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    required = ["schema_version", "status", "surprise_source", ...
        "dataset_name", "source_file", "source_file_sha256", ...
        "step6_panel_file", "step6_panel_sha256", ...
        "step6_match_summary_file", "step6_match_summary_sha256", ...
        "step6_script_sha256", "source_config_sha256", ...
        "source_reader_sha256", "manifest_writer_sha256"];
    missing = required(~ismember(required, ...
        string(manifest.Properties.VariableNames)));
    if height(manifest) ~= 1 || ~isempty(missing)
        error('SURPRISE_SOURCE_MANIFEST_INVALID: malformed %s.', manifestFile);
    end

    codeRoot = fileparts(which('Require_surprise_source_manifest'));
    panelFile = fullfile(projectRoot, manifest.step6_panel_file(1));
    matchFile = fullfile(projectRoot, manifest.step6_match_summary_file(1));
    outputsExist = exist(panelFile, 'file') == 2 && ...
        exist(matchFile, 'file') == 2;
    outputHashesMatch = outputsExist && ...
        File_sha256(panelFile) == manifest.step6_panel_sha256(1) && ...
        File_sha256(matchFile) == manifest.step6_match_summary_sha256(1);
    codeHashesMatch = ...
        File_sha256(fullfile(codeRoot, 'Press_release_panel.m')) == ...
            manifest.step6_script_sha256(1) && ...
        File_sha256(fullfile(codeRoot, 'Surprise_source_config.m')) == ...
            manifest.source_config_sha256(1) && ...
        File_sha256(fullfile(codeRoot, 'Read_ea_policy_window.m')) == ...
            manifest.source_reader_sha256(1) && ...
        File_sha256(fullfile(codeRoot, 'Write_surprise_source_manifest.m')) == ...
            manifest.manifest_writer_sha256(1);
    expectedHash = File_sha256(source.file_path);
    ok = manifest.schema_version(1) == source.schema_version & ...
        manifest.status(1) == "complete" & ...
        manifest.surprise_source(1) == source.source_id & ...
        manifest.dataset_name(1) == source.dataset_name & ...
        manifest.source_file(1) == string(source.relative_path) & ...
        manifest.source_file_sha256(1) == expectedHash & ...
        outputHashesMatch & codeHashesMatch;
    if ~ok
        error(['SURPRISE_SOURCE_MANIFEST_MISMATCH: selected %s does not match ' ...
            'the Step-6 manifest. Rerun the pipeline from Step 6.'], ...
            source.source_id);
    end
end
