function decision = Run_step28()
%RUN_STEP28 Verify Step 28A and enforce the sequential stopping rule.
%
% A data-gate failure is a protocol stop and is therefore recorded rather
% than raised as a MATLAB error.  The analytic SBB kernel is always tested,
% but empirical costs are never produced before every upstream gate passes.

    projectRoot = Get_project_root();
    fprintf('\n[28 preflight] Exact Dirac--Gaussian SBB kernel\n');
    SBB_dirac_gaussian_self_test();

    fprintf('\n[28A] Barchart Schatz--Bobl--Bund data gate\n');
    [decision, audit] = Step28_data_gate(projectRoot);
    fprintf('Binding checks passed: %d/%d\n', ...
        sum(audit.pass & audit.binding), sum(audit.binding));
    fprintf('Step-28 data status: %s\n', decision.status(1));

    if ~String_to_boolean(decision.ready_for_sample_size_gate(1))
        selector = upper(replace(strtrim(string(getenv('SURPRISE_SOURCE'))), ...
            "-", "_"));
        if strlength(selector) == 0; selector = "EA_EMPD"; end
        write_stage_decision(projectRoot, "blocked_data_gate", false, ...
            decision.next_action(1), selector, "not_checked_before_data_gate");
        fprintf('Step 28 stopped before spectral estimation: %s\n', ...
            decision.next_action(1));
        return;
    end

    % These identities become binding only after the independent market-data
    % gate passes.  They prevent an acquired SBB panel from being combined
    % with upstream outputs produced under another surprise workbook.
    source = Surprise_source_config(projectRoot);
    Require_time_alignment_manifest(projectRoot);
    Require_surprise_source_manifest(projectRoot, source);

    write_stage_decision(projectRoot, ...
        "ready_for_outcome_free_sample_size_calibration", false, ...
        ["inspect the certified coverage counts; freeze the synthetic " ...
        "spectral calibration before reading event returns"], ...
        string(source.source_id), File_sha256(source.file_path));
    fprintf(['Step 28A passed. The deliberate stopping point is the ' ...
        'outcome-free sample-size calibration.\n']);
end

function write_stage_decision(projectRoot, status, authorised, nextAction, ...
        sourceId, sourceHash)
    stageDecision = table("step28_stage_gate_v1", string(status), ...
        logical(authorised), string(nextAction), string(sourceId), ...
        string(sourceHash), ...
        string(datetime('now', 'TimeZone', 'UTC'), ...
        'yyyy-MM-dd''T''HH:mm:ssXXX'), ...
        'VariableNames', {'schema_version', 'status', ...
        'empirical_sbb_authorised', 'next_action', 'surprise_source', ...
        'surprise_source_sha256', 'generated_at_utc'});
    outputDir = fullfile(projectRoot, 'Output', 'step28_sbbts');
    writetable(stageDecision, fullfile(outputDir, ...
        'step28_stage_gate_decision.csv'));
end
