function [decision, audit] = Step28_data_gate(projectRoot)
%STEP28_DATA_GATE Verify the outcome-free Barchart data-preparation stage.
%
% The raw-file audit and canonical panel are produced by
% step28_prepare_barchart.py. This MATLAB boundary rechecks identities and
% hashes before any sample-size calibration or empirical estimator can run.

    if nargin < 1 || strlength(strtrim(string(projectRoot))) == 0
        projectRoot = Get_project_root();
    end

    outputDir = fullfile(projectRoot, 'Output', 'step28_sbbts');
    decisionFile = fullfile(outputDir, 'step28_data_gate_decision.csv');
    auditFile = fullfile(outputDir, 'step28_data_gate_audit.csv');
    manifestFile = fullfile(outputDir, 'step28_barchart_data_manifest.csv');

    requiredFiles = string({decisionFile, auditFile, manifestFile});
    missing = requiredFiles(~isfile(requiredFiles));
    if ~isempty(missing)
        error(['STEP28_BARCHART_PREFLIGHT_MISSING: run ' ...
            'python3 step28_prepare_barchart.py <Econometrics_data> first. ' ...
            'Missing: %s'], strjoin(missing, ' | '));
    end

    decision = readtable(decisionFile, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    audit = readtable(auditFile, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    manifest = readtable(manifestFile, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');

    if height(decision) ~= 1 || height(manifest) ~= 1
        error('STEP28_DATA_GATE_SCHEMA: decision and manifest need one row.');
    end

    decisionRequired = ["schema_version", "status", ...
        "ready_for_sample_size_gate", "failed_checks", "next_action", ...
        "data_provider", "data_manifest_sha256"];
    manifestRequired = ["schema_version", "status", "data_provider", ...
        "raw_time_zone", "raw_bar_label_semantics", ...
        "canonical_time_zone", "canonical_bar_label_semantics", ...
        "frequency_minutes", "raw_price_field", ...
        "canonical_price_field", "n_required_contracts", ...
        "n_present_contracts", "n_valid_contracts", ...
        "file_audit_sha256", "canonical_bars_sha256", ...
        "phase_coverage_sha256", "code_sha256", "primary_panel_ready"];
    require_columns(decision, decisionRequired, 'decision');
    require_columns(manifest, manifestRequired, 'manifest');

    validation = empty_validation();
    actualManifestHash = File_sha256(manifestFile);
    validation = add_validation(validation, "manifest_identity", ...
        decision.data_manifest_sha256(1) == actualManifestHash, ...
        actualManifestHash, decision.data_manifest_sha256(1), manifestFile);
    validation = add_validation(validation, "provider", ...
        decision.data_provider(1) == "Barchart" && ...
        manifest.data_provider(1) == "Barchart", ...
        decision.data_provider(1) + ";" + manifest.data_provider(1), ...
        "Barchart;Barchart", manifestFile);
    validation = add_validation(validation, "clock_and_fields", ...
        manifest.raw_time_zone(1) == "America/Chicago" && ...
        manifest.raw_bar_label_semantics(1) == "interval_start" && ...
        manifest.canonical_time_zone(1) == "UTC" && ...
        manifest.canonical_bar_label_semantics(1) == "interval_end" && ...
        numeric_value(manifest.frequency_minutes(1)) == 5 && ...
        manifest.raw_price_field(1) == "Latest" && ...
        manifest.canonical_price_field(1) == "Close", ...
        manifest.raw_time_zone(1) + ";" + ...
        manifest.raw_bar_label_semantics(1) + ";" + ...
        manifest.canonical_time_zone(1) + ";" + ...
        manifest.canonical_bar_label_semantics(1), ...
        "America/Chicago;interval_start;UTC;interval_end", manifestFile);
    validation = add_validation(validation, "contract_universe", ...
        numeric_value(manifest.n_required_contracts(1)) == 165 && ...
        numeric_value(manifest.n_present_contracts(1)) == 165 && ...
        numeric_value(manifest.n_valid_contracts(1)) == 165, ...
        string(manifest.n_required_contracts(1)) + ";" + ...
        string(manifest.n_present_contracts(1)) + ";" + ...
        string(manifest.n_valid_contracts(1)), "165;165;165", manifestFile);

    hashFiles = ["step28_barchart_file_audit.csv"; ...
        "step28_canonical_bars.csv"; "step28_phase_coverage.csv"];
    expectedHashes = [manifest.file_audit_sha256(1); ...
        manifest.canonical_bars_sha256(1); manifest.phase_coverage_sha256(1)];
    for i = 1:numel(hashFiles)
        path = fullfile(outputDir, hashFiles(i));
        passed = isfile(path) && File_sha256(path) == expectedHashes(i);
        observed = "missing";
        if isfile(path); observed = File_sha256(path); end
        validation = add_validation(validation, "hash_" + ...
            erase(hashFiles(i), ".csv"), passed, observed, ...
            expectedHashes(i), path);
    end

    codeFile = fullfile(fileparts(which('Step28_data_gate')), ...
        'step28_prepare_barchart.py');
    codePass = isfile(codeFile) && ...
        File_sha256(codeFile) == manifest.code_sha256(1);
    codeObserved = "missing";
    if isfile(codeFile); codeObserved = File_sha256(codeFile); end
    validation = add_validation(validation, "preparation_code_identity", ...
        codePass, codeObserved, manifest.code_sha256(1), codeFile);

    pythonReady = String_to_boolean(decision.ready_for_sample_size_gate(1)) && ...
        String_to_boolean(manifest.primary_panel_ready(1)) && ...
        decision.status(1) == "pass_data_gate" && ...
        manifest.status(1) == "certified";
    allValid = pythonReady && all(validation.pass);
    validationFile = fullfile(outputDir, ...
        'step28_matlab_gate_validation.csv');
    writetable(validation, validationFile);

    if ~allValid
        failed = validation.check_id(~validation.pass);
        prior = strtrim(string(decision.failed_checks(1)));
        if strlength(prior) > 0; failed = [prior; failed]; end
        decision.status(1) = "blocked_data_gate";
        if isnumeric(decision.ready_for_sample_size_gate) || ...
                islogical(decision.ready_for_sample_size_gate)
            decision.ready_for_sample_size_gate(1) = 0;
        else
            decision.ready_for_sample_size_gate(1) = "0";
        end
        decision.failed_checks(1) = strjoin(failed, '|');
        decision.next_action(1) = ...
            "repair failed Barchart data identities and rerun Step 28";
    end

    audit = normalise_audit(audit);
    validationAudit = table(validation.check_id, true(height(validation), 1), ...
        validation.pass, validation.observed, validation.required, ...
        validation.source_file, validation.source_sha256, ...
        'VariableNames', audit.Properties.VariableNames);
    audit = [audit; validationAudit];
end

function require_columns(T, required, label)
    missing = required(~ismember(required, string(T.Properties.VariableNames)));
    if ~isempty(missing)
        error('STEP28_%s_SCHEMA: missing %s.', upper(label), ...
            strjoin(missing, ', '));
    end
end

function value = numeric_value(value)
    if isnumeric(value)
        value = double(value);
    else
        value = str2double(string(value));
    end
end

function T = empty_validation()
    T = table('Size', [0, 6], 'VariableTypes', ...
        {'string', 'logical', 'string', 'string', 'string', 'string'}, ...
        'VariableNames', {'check_id', 'pass', 'observed', 'required', ...
        'source_file', 'source_sha256'});
end

function T = add_validation(T, id, passed, observed, required, source)
    source = string(source);
    sourceHash = "missing";
    if isfile(source); sourceHash = File_sha256(source); end
    row = table(string(id), logical(passed), string(observed), ...
        string(required), source, sourceHash, ...
        'VariableNames', T.Properties.VariableNames);
    T = [T; row]; %#ok<AGROW>
end

function audit = normalise_audit(audit)
    required = ["check_id", "binding", "pass", "observed", ...
        "required", "source_file", "source_sha256"];
    require_columns(audit, required, 'audit');
    audit = audit(:, cellstr(required));
    audit.check_id = string(audit.check_id);
    audit.binding = String_to_boolean(audit.binding);
    audit.pass = String_to_boolean(audit.pass);
    audit.observed = string(audit.observed);
    audit.required = string(audit.required);
    audit.source_file = string(audit.source_file);
    audit.source_sha256 = string(audit.source_sha256);
end
